### ISSUE TITLE
请问可以将你的网站放到 gopl 在线预览列表中吗？

### ISSUE THREAD

**Issue by ziyitony** [ykfq/img#1]
你好，我一直在看你的 [gopl 在线预览](https://book.itsfun.tk/gopl-zh/)。自动更新，访问速度快，是我目前找到最好的镜像，真的很感谢你！！！

但是该网站不在[在线预览列表](https://github.com/gopl-zh/gopl-zh.github.com#%E5%9C%A8%E7%BA%BF%E9%A2%84%E8%A7%88)中。请问可以将你的网站放到该列表中吗？

在你的网站上找不到你的联系方式，只好在这里发 Issue ，如有不便请见谅。

**Comment by ykfq** [comment]
> 你好，我一直在看你的 [gopl 在线预览](https://book.itsfun.tk/gopl-zh/)。自动更新，访问速度快，是我目前找到最好的镜像，真的很感谢你！！！
> 
> 但是该网站不在[在线预览列表](https://github.com/gopl-zh/gopl-zh.github.com#%E5%9C%A8%E7%BA%BF%E9%A2%84%E8%A7%88)中。请问可以将你的网站放到该列表中吗？
> 
> 在你的网站上找不到你的联系方式，只好在这里发 Issue ，如有不便请见谅。

@ziyitony  这个要去 gopl 的仓库提交一下链接才行。我试试看

这个地址已经换成 https://book.itsfun.top/gopl-zh 了，依然每天自动构建，持续更新。
之前的域名是在 freenom 申请的免费域名，总是莫名其妙的就被删除调了，现在的域名是买的。

**Comment by ykfq** [comment]
已经放进去了。
